name: reducio
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  file_picker: ^10.1.9
  path_provider: ^2.1.5
  dotted_border: ^2.1.0
  desktop_drop: ^0.6.0
  archive: ^4.0.7
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/ffmpeg/linux/ffmpeg.zip
    # - assets/ffmpeg/macos/ffmpeg.zip
    # - assets/ffmpeg/windows/ffmpeg.zip
    - assets/icons/compress.png
    - assets/icons/mute.png
  
  fonts:
    - family: HarryPotter
      fonts:
        - asset: assets/fonts/HarryPotter.ttf